apiVersion: apps/v1
kind: Deployment
metadata:
  name: crowd-fund-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: crowd-fund-app
  template:
    metadata:
      labels:
        app: crowd-fund-app
    spec:
      containers:
        - name: crowd-fund-container
          image: username/crowd-fund-app:latest
          ports:
            - containerPort: 8080
